# Generated by Django 4.2 on 2023-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='name',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='no description available', help_text='Description of the snack', max_length=255),
        ),
        migrations.AddField(
            model_name='snack',
            name='title',
            field=models.CharField(default='unknown', help_text='snack title', max_length=255),
        ),
    ]
